---
abstract: 'universal website visitors tracking'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
keywords:
  - web
  - www
  - tracking
  - analytics
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Tracking
provides:
  WWW::Tracking:
    file: lib/WWW/Tracking.pm
    version: 0.01
  WWW::Tracking::Data:
    file: lib/WWW/Tracking/Data.pm
    version: 0.01
  WWW::Tracking::Data::Plugin::Catalyst:
    file: lib/WWW/Tracking/Data/Plugin/Catalyst.pm
    version: 0
  WWW::Tracking::Data::Plugin::GoogleAnalytics:
    file: lib/WWW/Tracking/Data/Plugin/GoogleAnalytics.pm
    version: 0
  WWW::Tracking::Data::Plugin::Headers:
    file: lib/WWW/Tracking/Data/Plugin/Headers.pm
    version: 0
requires:
  CGI::Cookie: 0
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Digest::MD5: 0
  HTTP::Headers: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  URI::Escape: 0
resources:
  bugtracker: http://github.com/jozef/WWW-Tracking/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jozef/WWW-Tracking
version: 0.01
